### ISSUE TITLE
assigning records from pointers causes error

### ISSUE THREAD

**Issue by luarockr** [lboasso/oberonc#1]
The code snipplet
     
    MODULE RecTest;
    
    TYPE RP = POINTER TO R;
      R = RECORD
      rp : RP;
      i : INTEGER;
    END;

    VAR
    globRP : RP;

    PROCEDURE DoSmth(locRP : RP);
    BEGIN
      globRP^.rp^ := locRP^;
      (*
      globRP^.rp^.rp := locRP^.rp;
      globRP^.rp^.i := locRP^.i;
      *)
    END DoSmth;
    
    BEGIN
    END RecTest.

Throws an error 
..\examples\RecTest.Mod:14:24: Reg Stack
..\examples\RecTest.Mod:19:12: compilation FAILED

Other compilers compile this assignment (e.g. Oxford)
Assigning single members works well with oberonc.

**Comment by lboasso** [comment]
Thank you for trying out oberonc and reporting this bug! 
I am working on a fix, I will push it in the coming few days.

**Comment by lboasso** [comment]
Fixed in commit 6dfbd389c9d8abffc0817a041911bac1fdb2c3c7

**Comment by luarockr** [comment]
works now, thanks a lot for the quick fix :-)
