### ISSUE TITLE
SYSTEM.VAL pointer conversions

### ISSUE THREAD

**Issue by johnperry-math** [lboasso/oberonc#10]
Hello

I tried to do an "unchecked" pointer-to-pointer conversion using `SYSTEM.VAL`. I discovered that (a) `oberonc` doesn't actually allow that in its current version, and (b) after I modified it to allow it, the performance seemed indistinguishable from a "checked" conversion via type guard.

To be clear, I'm talking about (unchecked)
```oberon
   y := SYSTEM.VAL(Ptr, x);
```
and (checked)
```oberon
   y := x(Ptr);
```
I could pass on (via pull request if need be) the modifications I made that enable the unchecked pointer-to-pointer conversion, but I'm not sure it's worth the effort if it makes no measurable difference in code. (It doesn't seem to make a difference in OBNC's implementation of `SYSTEM.VAL`, either, and from what I can tell that does a direct C typecast.)

I would be interested in your thoughts on this.

(Some detail: I modified `StandFunc` when `fct = 16` to invoke a new `OJG.PointerToPointer` procedure when `x` and `y` are both pointers. `OJG.PointerToPointer` then generates a `CHECKCAST` opcode. As it turns out, this seems to generate the exact same byte code as a type guard, so perhaps there's a better way to make an unchecked pointer-to-pointer conversion, but that's the best I could divine from my very limited knowledge of JVM byte codes. Plus, it also seems to be what the Java language it does when you cast. But I'm just learning, so...)

**Comment by johnperry-math** [comment]
Oh -- and my attempts to implement the unchecked typecast in any fashion that did not involve `CHECKCAST` always led to verification errors in the Java executable, but again, it's not as if I actually know what I'm doing. :-)

**Comment by lboasso** [comment]
Hi John!

The Java Virtual Machine was designed to be type safe and the bytecode verifier will enforce that, before executing any instruction. This explains the issues you encountered  by not using the `CHECKCAST` instruction. 
It is possible to implement some unsafe features of the pseudo-module SYSTEM with the now deprecated `sun.misc.Unsafe` class or similar platform depended hooks. I have not found a compelling reason to do so. Could you explain to me what you are trying to achieve with SYSTEM? Performance should not be a concern given the excellent JVM implementations available today.

**Comment by johnperry-math** [comment]
Thank you for the reply!

I'm trying to write a program that works with multiple Oberon compilers. Suppose `x` is a pointer. There are times where it's convenient to write `x(T)` without first checking whether `x` is `NIL`.

If `x` is a pointer with the value `NIL`, then the OBNC compiler (v0.15.0) aborts on `x(T)`. On the other hand, oberonc is fine with it. It's not clear to me whether this is a bug in OBNC or just undefined behavior in Oberon; Wirth doesn't seem to address the possibility.

On the other hand, OBNC is happy with `l := SYSTEM.VAL(T, x);`, but if x is a pointer and `T` is a pointer type then oberonc gives a compiler-time error, because `OJP.Mod` doesn't implement `SYSTEM.VAL` for pointer types.

Alternately I could write `IF x # NIL THEN x(T) ELSE NIL END` but I'd rather avoid that if I could. It seems to me, however, that I can't.

**Comment by lboasso** [comment]
It is undefined behaviour, the language report leaves this case unspecified. I chose to follow the semantic of  the `CHECKCAST` instruction that does nothing if the value is null, see the [specification](https://docs.oracle.com/javase/specs/jvms/se12/html/jvms-6.html#jvms-6.5.checkcast).

`SYSTEM.VAL(T, x)` should not generate any code for a native compiler, since types are a compiler concept and we are just telling the compiler to trust us and use type `T` for `x`. This is not possible in the JVM where the types are enforced at run-time for type safety (you could create a program that corrupts your system otherwise). 
It is possible to write a program that works on multiple compilers, `oberonc` differs from ` OBNC` only on **when** the error happens at runtime:

```
MODULE M;
  TYPE
    pR = POINTER TO R;
    pR1 = POINTER TO R1;
    R = RECORD a: BYTE END;
    R1 = RECORD(R) b: BYTE END;

  VAR
    x, t: pR1;
    y: pR; res: BYTE;

BEGIN
  (* NEW(x); *)
  x := NIL;
  y := x;
  t := y(pR1);  (* Error at runtime for OBNC *)
  res := t.b;      (* Error at runtime for oberonc, when we access a field of t *)
END M.
```
This example is a bit contrived, usually one would simply write `y(pR1).b` and in both compilers you will get a failure when y is NIL. In general when writing robust code, you should check for NIL pointers.

**Comment by johnperry-math** [comment]
I didn't include a fuller example that motivated my question (adapted, not verbatim):
```modula-2
TYPE
   List = RECORD next: List END;
   List2 = RECORD (List) prev: List2 END;

(*...*)

PROCEDURE Iterate(L: List2);
BEGIN
   WHILE L # NIL DO
      doSomethingWith(L);
      L := L.next(List2)
   END;
END Iterate;
```
OBNC aborts at run-time when `L` reaches the end of the list, but not if we write it this way:
```modula-2
   WHILE L # NIL DO
      doSomethingWith(L);
      L := SYSTEM.VAL(List2, L.next)
   END;
```
On the other hand, oberonc won't compile this without the modifications I mentioned earlier.

In my particular example I actually found a workaround by changing the type of `L` to `List` instead of `List2`, because one doesn't actually need `prev` in the situation, but I suspect that there are cases where that would be necessary. I'm trying to write some code that works with generic containers, and Oberon's type rules imply that if you pass a procedure as an argument, then you *have* to give the most general arguments possible, and that then requires some sort of type guard or cast, and you might have `NIL`.

**Comment by lboasso** [comment]
I see your point. Presumably `List` stands for single linked list, while `List2` for double linked list. You are using a type extension to share as much as possible the implementation of the two kinds of list.

In general you should stay away from undefined corners of the language report and make use of SYSTEM only when implementing low level modules (unlike your generic container library). I checked the implementation of Wirth's RISC compiler and it handles NIL the same way I do, while older Oberon-2 compilers trap when NIL is used in a type guard. I believe the current behaviour of `oberonc` is the right one.

**Comment by johnperry-math** [comment]
> I believe the current behaviour of oberonc is the right one.

OK, great, thanks. I agree that using a type guard is a much better idea. I take it you don't want to enable `SYSTEM.VAL` to work with pointers?

**Comment by johnperry-math** [comment]
BTW, I found a conversation I had with OBNC's developer back in October where he says that applying a type guard to `NIL` is undefined, so it looks as if I'll have to resort to `IF` statements. :-)

**Comment by lboasso** [comment]
>  I take it you don't want to enable SYSTEM.VAL to work with pointers?

I wish I could implement it but it's not possible to do it in a portable way in the JVM. Since it breaks bytecode verification guarantees you need to resort to hacks  specific to each JVM implementation.

**Comment by johnperry-math** [comment]
I just meant to implement with `CHECKCAST`, i.e., do the same thing as with type guards. I've done that in my copy of your compiler, and it works there; is that not portable? I didn't meant to do something more than that.

Sorry to be such a bother; it really doesn't mean *that* much to me; I'm just curious about your reply.

**Comment by lboasso** [comment]
I am sorry, I misunderstood you. So your proposal is to make the implementation of `SYSTEM.VAL` equivalent to the one of a type guard. It is a good compromise, the full implementation would allow any kind of type conversions, even unsafe ones, something that it's hard to do on the JVM. 
If you have already implemented this, I would happily accept your changes as a pull request. Otherwise I'll add the functionality myself.
