### ISSUE TITLE
Bug with invalid pointers

### ISSUE THREAD

**Issue by johnperry-math** [lboasso/oberonc#12]
There seems to be a bug in `internalNameAt` that manifests with this code:
```modula-2
MODULE TestPt;
TYPE
  PT = POINTER TO ARRAY 5 OF BOOLEAN;
VAR
  pt: PT;
BEGIN
  pt := NIL;
END TestPt.
```
The output I get is
```
$ java -cp $OBERON_BIN oberonc build TestPt.obn 
TestPt.obn:5:37: must point to record
Exception in thread "main" java.lang.NullPointerException
	at OJG.internalNameAt(OJG.Mod:139)
	at OJG.DescriptorR(OJG.Mod:171)
	at OJG.DescriptorAt(OJG.Mod:209)
	at OJG.Descriptor(OJG.Mod:214)
	at OJG.Header(OJG.Mod:2310)
	at OJP.Module(OJP.Mod:1378)
	at OJP.Compile(OJP.Mod:1410)
	at oberonc.Main(oberonc.Mod:40)
	at oberonc.main(oberonc.Mod)
```
It looks as if it's because `type.base.typobj` is `NIL`. If I change it as follows:
```modula-2
      IF type.base.typobj # NIL THEN
        i := Strings.Write(type.base.typobj.name, out, i)
      ELSE
        i := Strings.Write(type.typobj.name, out, i)
      END
```
...then the compiler doesn't crash. Though maybe it doesn't need the `ELSE` case anyway; could it be left blank?

**Comment by lboasso** [comment]
Thanks for reporting this bug.
I have pushed a [fix](https://github.com/lboasso/oberonc/commit/790e53f4226296c3237c39542c0d58e6d2f2aeb1) for this, together with another unrelated fix.
Like in other parts of the compiler, when we have a type error, we report it and set the type to a dummy `INTEGER` so that we resume in stable state.

**Comment by johnperry-math** [comment]
Thanks; I merged it to my fork.

Here's a related issue that might not actually be a bug. In the code below, `A` is never defined, but I can assign `NIL` to a pointer to `A`. My impression from reading 6.4 of *The Programming Language Oberon* is that `A` should be defined, but perhaps not?
```modula-2
MODULE TestPtr;

TYPE
  PT = POINTER TO A; (* A is undefined *)

VAR
  pt: PT;

BEGIN (* A is still undefined *)
  pt := NIL;
END TestPtr.
```

**Comment by lboasso** [comment]
This is a bug, this example should not compile. I'll push a fix soon.
Thanks for reporting this issue!

**Comment by lboasso** [comment]
Please try out the new [fix](https://github.com/lboasso/oberonc/commit/c235c2d84be89edc16329af1a00ab750036db7b1) in master. Thanks!

**Comment by johnperry-math** [comment]
It works!
