### ISSUE TITLE
CASE statements & tableswitch

### ISSUE THREAD

**Issue by johnperry-math** [lboasso/oberonc#14]
This code won't compile:
```modula-2
MODULE TestCase;
IMPORT Out;
VAR a: INTEGER;
BEGIN
  a := 10;
  CASE a OF
     5: Out.String("Five")
  | 10: Out.String("Ten")
  | 15: Out.String("Fifteen")
  | 2000: Out.String("Two thousand!!!")
  END;
  Out.Ln
END TestCase.
```
The output is
```
TestCase.obn:11:0: too many cases or no case in case statement
TestCase.obn:13:13: compilation FAILED
```
Apparently the problem is that the compiler wants to use a `tableswitch`, and limits the number of cases to a maximum of 256. From what I read about the JVM, a `lookupswitch` is a better option in this case.

I have a workaround for now (the obvious one that uses `IF`).

**Comment by lboasso** [comment]
You are right, this is a conscious limitation. Usually in Wirth's compilers case statements are implemented with tables (with an arbitrary limit of 256 entries), that is why I used the `tableswitch` instruction of the JVM for `oberonc`. Tables work well when the case labels are contiguous and not so sparse. It is possible to selectively compile the case statement to a `tableswitch` or `lookupswitch` based on the label distribution, but I don't think it is worth it for a single-pass compiler.
