### ISSUE TITLE
jar integration

### ISSUE THREAD

**Issue by Jack-Ji** [lboasso/oberonc#15]
any chance I can import and use other jars directly in Oberon?

**Comment by lboasso** [comment]
Hi Jack, 
thanks for trying out oberonc. 

Have you looked at the [fern](https://github.com/lboasso/oberonc/tree/master/examples/fern) example? I am assuming you want to use a jar with java code in it.
To call java code in oberonc you need a `DEFINITION` module. For example [MathUtil.Mod](https://github.com/lboasso/oberonc/blob/master/examples/fern/MathUtil.Mod) will allow you to call the implementation code in [MathUtil.java](https://github.com/lboasso/oberonc/blob/master/examples/fern/java/MathUtil.java).  As long as the java .class file is in in the class path (in a jar or not) it should just work.

Let me know

**Comment by Jack-Ji** [comment]
Hi @lboasso, thank you for your kind response. I think fern is an OK example, since an DEFINITION file is needed, and only static methods can be used. I am hoping to use other jar without too much trouble

**Comment by lboasso** [comment]
I agree the current Java support is minimal. Feel free to extend it and send a pull request, I would happily accept it

**Comment by Jack-Ji** [comment]
Sure, I’ll try to figure what I can do. But I don’t use java very often, can’t promise anything for now

**Comment by lboasso** [comment]
OK let me know, closing this
