### ISSUE TITLE
Could you help with continue development of gpcp-JVM?

### ISSUE THREAD

**Issue by 3oheicrw** [lboasso/oberonc#20]
The developer of it is a long way past retirement age. There is no development since 2018. You wrote and maintaining oberonc. You are an expert at the JVM bytecode, don't you? Could you help that project? I came across it today. I feel the language has potential but sadly it's currently in bad state.

https://github.com/k-john-gough/gpcp/issues/13

**Comment by lboasso** [comment]
Unfortunately I have very little free time so I will not be able to contribute to that project.
