### ISSUE TITLE
[Question] Which language revision does your implementation supports?

### ISSUE THREAD

**Issue by rbatllet** [lboasso/oberonc#24]
Oberon-07, defined by Niklaus Wirth in 2007, has been revised in 2008, 2011, 2013, 2013, 2014, 2015 and finally in 2016.

Could you please let us know up to which year your compiler implementation supports?

Link: https://online.oberon.org/oberon_en

**Comment by lboasso** [comment]
The latest (2016) but I have documented a bit more precisely the type rules [here](https://github.com/lboasso/oberonc/blob/master/doc/TypeRules.md).
