### ISSUE TITLE
[Proposal] Liberapay or OpenCollective to support the project

### ISSUE THREAD

**Issue by EchedeyLR** [lboasso/oberonc#25]
Hi.

I am new to Oberon language family and got some interest since your compiler seemed one of the most active projects, simpler to build and use listed at https://oberon.org.

I also like the perspective of Oberon being a JVM language with this.

Is there any way to support you and your project?

**Comment by lboasso** [comment]
Hello EchedeyLR!

Sorry for the late reply but I was traveling.
Thanks for the kind words! 
Currently I am not planning to set up a donation program, the best way to support me and my project would be to report bugs and use `oberonc` to build things :)

Cheers,
Luca
