### ISSUE TITLE
Need list of language expression that compiler do understand correctly

### ISSUE THREAD

**Issue by upiter20** [lboasso/oberonc#35]
Good day. Saw many bug reports of using compiler. As far as I understand the compiler does not understand some language expression. Would you please write the list of languge expressions, declaration if variables and so on that compiler do understand correctly, so I could use them in my code?

**Comment by lboasso** [comment]
Hello, 
There are no known issues with the compiler. I suggest you read [Programming in Oberon (a Tutorial) ](https://people.inf.ethz.ch/wirth/Oberon/PIO.pdf) so that you can better understand how the language is used. 
If you find any bugs please let me know.

Happy programming, 
Luca
