### ISSUE TITLE
Changes to make it easy to recompile

### ISSUE THREAD

**Issue by johnperry-math** [lboasso/oberonc#7]
Here's another issue I found while trying to find the problem I was having. The Makefile has the following lines:

    MOD_SOURCES = src/Out.Mod src/Os.Mod src/Files.Mod src/Strings.Mod src/OJS.Mod \
                  src/CpCache.Mod src/Opcodes.Mod src/ClassFormat.Mod+ src/OJB.Mod \
                  src/OJG.Mod src/OJP.Mod src/oberonc.Mod

As is, making a change to the compiler will lead to an error, something like "New symbol file inhibited." This is because the compiler, by default, doesn't want to overwrite a symbol file. Unfortunately, the compiler actually deletes the old class file(s) first (personally, I think this is a bug) so now the compiler doesn't work anymore. ***Argh*** **thunk** *as head slams against table in Don Music style*

Changing it to the following makes it possible to overwrite those class files, recompile the compiler, and so forth. ***Joy!!!*** **smiles** 

    MOD_SOURCES = src/Out.Mod+ src/Os.Mod src/Files.Mod+ src/Strings.Mod+ src/OJS.Mod+ \
                  src/CpCache.Mod+ src/Opcodes.Mod+ src/ClassFormat.Mod+ src/OJB.Mod+ \
                  src/OJG.Mod+ src/OJP.Mod+ src/oberonc.Mod+

**Comment by johnperry-math** [comment]
> Unfortunately, I did not document my work flow when I modify the compiler's sources, sorry for the trouble you had. Usually, I make a copy of the current binary folder bin to a separate folder, for example bin2; then I point OBERON_BIN to it, so that I can keep running the old and working version of the compiler while developing new features.

I see how that works. Maybe that can be part of the Makefile? Of course one can do it manually; it's just that when it fails, it's rather fatal, since at least one class files will be gone.

**Comment by lboasso** [comment]
You are right, what if I change `make build2` to output the files in a new `build` folder?

**Comment by lboasso** [comment]
I don't like making the build too smart. I decided to add a `make bootstrap` and change `make build` as follows:

> By typing `make build` on the shell, the compiler will compile itself and write the files in the `out` folder. The `make bootstrap` command is equivalent to `make build`, but it overwrites the files in the `bin` folder.

I hope this is a good compromise.

**Comment by johnperry-math** [comment]
That sounds great!

**Comment by lboasso** [comment]
Awesome!
