### ISSUE TITLE
Tests fails because of locales, that differ from en_US

### ISSUE THREAD

**Issue by ComdivByZero** [lboasso/oberonc#8]
For example:

    $ LANG=ru_RU.UTF-8 make test
    ...
    Test 'tests/base/TestImport62.Mod' FAILED:
    EXPECTING:
    'AY 3.140000 -999999999'
    FOUND:
    'AY 3,140000 -999999999'
    ---END---
 
    TOTAL: 97
    SUCCESSFUL: 85
    FAILED: 12

Other example:

    $ LANG=en_UK.UTF-8 make test
    ...
    Test 'tests/base/UTF8String.Mod' FAILED:
    EXPECTING:
    'Hello, ? ?'
    FOUND:
    'Hello, ? ?'
    ---END---
    ...
    TOTAL: 97
    SUCCESSFUL: 95
    FAILED: 2

**Comment by lboasso** [comment]
Thanks for reporting this issue. I'll fix it soon.

**Comment by lboasso** [comment]
I pushed a [fix](https://github.com/lboasso/oberonc/commit/3c685a027b0ca5c01c47df4f353b8f17e5ecb28d) on master, please try it out and see if it works for you.

**Comment by ComdivByZero** [comment]
Yes, it works
