### ISSUE TITLE
IN Module

### ISSUE THREAD

**Issue by dukester** [lboasso/oberonc#9]
Is there such a module to get user input.  Very Important to have one!!  Thx.

**Comment by lboasso** [comment]
Hello, thanks for your interest in `oberonc`!
You are right, I forgot to implement the `In` module.
I just added an implementation, it differs from the original one found in the Oberon System. Please refer to the documentation in `src/In.Mod`
You can try out the example `examples/GuessNumber.Mod` using the new `In` module:

```
Linux
java -cp $OBERON_BIN oberonc . examples/GuessNumber.Mod
java -cp $OBERON_BIN:. GuessNumber

Windows
java -cp %OBERON_BIN% oberonc . examples/GuessNumber.Mod
java -cp %OBERON_BIN%;. GuessNumber
```
Let me know what you think.

**Comment by lboasso** [comment]
The issue has been addressed, closing.
